import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Example from './example'
import CustomCard from './CustomCard'

import { useState } from 'react';
import {
    Block,
    Card,
    ColGrid,
    Tab,
    TabList,
    Text,
    Title,
    BadgeDelta,
    DeltaType,
    Flex,
    Metric,
    ProgressBar,

    Table,
    TableHead,
    TableHeaderCell,
    TableBody,
    TableRow,
    TableCell,
    Badge,
    Icon
} from "@tremor/react";

type Kpi = {
  title: string,
  metric: string,
  progress: number,
  target: string,
  delta: string,
  deltaType: DeltaType,
}

const kpiData: Kpi[] = [
  {
      title: 'Sales',
      metric: '$ 12,699',
      progress: 15.9,
      target: '$ 80,000',
      delta: '13.2%',
      deltaType: 'moderateIncrease',
  },
  {
      title: 'Profit',
      metric: '$ 45,564',
      progress: 36.5,
      target: '$ 125,000',
      delta: '23.9%',
      deltaType: 'increase',
  },
  {
      title: 'Customers',
      metric: '1,072',
      progress: 53.6,
      target: '2,000',
      delta: '10.1%',
      deltaType: 'moderateDecrease',
  }
];

const Home: NextPage = () => {

  const data = [
    {
      name: "Viola Amherd",
      Role: "Federal Councillor",
      departement:
        "The Federal Department of Defence, Civil Protection and Sport (DDPS)",
      status: "active",
    },
    {
      name: "Simonetta Sommaruga",
      Role: "Federal Councillor",
      departement:
        "The Federal Department of the Environment, Transport, Energy and Communications (DETEC)",
      status: "active",
    },
    {
      name: "Alain Berset",
      Role: "Federal Councillor",
      departement: "The Federal Department of Home Affairs (FDHA)",
      status: "active",
    },
    {
      name: "Ignazio Cassis",
      Role: "Federal Councillor",
      departement: "The Federal Department of Foreign Affairs (FDFA)",
      status: "active",
    },
    {
      name: "Ueli Maurer",
      Role: "Federal Councillor",
      departement: "The Federal Department of Finance (FDF)",
      status: "active",
    },
    {
      name: "Guy Parmelin",
      Role: "Federal Councillor",
      departement:
        "The Federal Department of Economic Affairs, Education and Research (EAER)",
      status: "active",
    },
    {
      name: "Karin Keller-Sutter",
      Role: "Federal Councillor",
      departement: "The Federal Department of Justice and Police (FDJP)",
      status: "active",
    },
  ];

  // render a tremor card
  const renderCard = (title: string, content: string) => {
    return (
      <Card>
        <Block>
          <Title>{title}</Title>
          <Text>{content}</Text>
        </Block>
      </Card>
    );
  }

  const renderTable = () => {
    return (
      <Card>
    <Title>List of Swiss Federal Councillours</Title>
    <Table marginTop="mt-5">
      <TableHead>
        <TableRow>
          <TableHeaderCell>Name</TableHeaderCell>
          <TableHeaderCell>Position</TableHeaderCell>
          <TableHeaderCell>Department</TableHeaderCell>
          <TableHeaderCell>Status</TableHeaderCell>
        </TableRow>
      </TableHead>
      <TableBody>
        {data.map((item) => (
          <TableRow>
            <TableCell>{item.name}</TableCell>
            <TableCell>
              <Text>{item.Role}</Text>
            </TableCell>
            <TableCell>
              <Text>{item.departement}</Text>
            </TableCell>
            <TableCell>
              <Badge
                text={item.status}
                color="emerald"
                Icon={Icon.StatusOnlineIcon}
              />
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  </Card>
    );
        }

  const renderKpi = () => {
    return (
    <ColGrid numColsMd={ 2 } numColsLg={ 3 } marginTop="mt-6" gapX="gap-x-6" gapY="gap-y-6">
            { kpiData.map((item) => (
                <Card key={ item.title }>
                    <Flex alignItems="items-start">
                        <Block truncate={ true }>
                            <Text>{ item.title }</Text>
                            <Metric truncate={ true }>{ item.metric }</Metric>
                        </Block>
                        <BadgeDelta deltaType={ item.deltaType } text={ item.delta } />
                    </Flex>
                    <Flex marginTop="mt-4" spaceX="space-x-2">
                        <Text truncate={ true }>{ `${item.progress}% (${item.metric})` }</Text>
                        <Text>{ item.target }</Text>
                    </Flex>
                    <ProgressBar percentageValue={ item.progress } marginTop="mt-2" />
                </Card>
            )) }
        </ColGrid>
    )
  }




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {renderCard("Title", "Content")}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        {renderKpi()}
        {renderTable()}
        {renderCard("Title", "Content")}

        <div className={styles.grid}>
          { /* render a tremor card */ }
          {renderCard("Title", "Content")}
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
          {renderTable()}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
